### ISSUE TITLE
Azure Dev Space VSCode extension breaks Python extension's debug cell function

### ISSUE THREAD

**Issue by rustedwizard** [Azure/dev-spaces#319] opened 2020-04-20 18:39 UTC
I seems like this extension (when installed and activated) breaks the debug cell function for Python extension (as I reported at https://github.com/microsoft/vscode-python/issues/10946). Please check the attached gif file, once Azure Dev Space extension activated, debug cell function for Python extension stops working.
![capture](https://user-images.githubusercontent.com/6314177/79787180-72a46500-82fb-11ea-9ddd-03d4e5c2cd14.gif)

My VSCode setup info:
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by daniv-msft** [comment] 2020-04-20 21:38
Thank you for reporting this issue, and sorry you encountered it.
I've been able to reproduce the bug you mention, and I found the root cause.

Our extension needs to intercept debug sessions for one of our core features, but unfortunately we don't act properly when a debug session is triggered by another extension with an undefined workspace folder.
This is what happened when you start debugging a Python cell.

I have a fix for this, and it should be released in the coming days. I'll update this issue once the fix is released.
I'll also update the other issue you opened so that the Python team knows this is not a bug on their side.

**Comment by daniv-msft** [comment] 2020-04-21 16:28
@rustedwizard We released today a new version of the Azure Dev Spaces VS Code extension including the bug fix (version 2.0.220200421).
I tested it and can confirm that the bug doesn't reproduce anymore after the update.

I'm closing this issue, but feel free to reopen it if you encounter any other issues.
Thank you again for this reporting this!

**Closed by daniv-msft** 2020-04-21 16:28 UTC

**Comment by rustedwizard** [comment] 2020-04-21 16:37
@daniv-msft Thanks, I have updated this extension and I can confirm it is working now.
