### ISSUE TITLE
Extension issue - Performance in my VS Code

### ISSUE THREAD

**Issue by davyb1964** [Azure/dev-spaces#266] opened 2020-01-10 23:11 UTC
[azuredevspaces.azds-unresponsive.cpuprofile.txt](https://github.com/Azure/dev-spaces/files/4048548/azuredevspaces.azds-unresponsive.cpuprofile.txt)```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 21768,
		"activateCallTime": 1,
		"activateResolvedTime": 158,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "azuredevspaces.azds",
				"_lower": "azuredevspaces.azds"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```
- Issue Type: `Bug`
- Extension Name: `azds`
- Extension Version: `2.0.220191204`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by daniv-msft** [comment] 2020-01-10 23:22
Thank you for reporting this performance issue!
I had a look quickly at the CPU profile you provided, and the issue has the same root cause as the one mentioned here: https://github.com/Azure/dev-spaces/issues/260

We have a fix for this, and it should be released soon (around 10 days from now).
I'm closing this issue as duplicate, but you can keep an eye on the other issue as I'll only close it when the fix becomes available.

**Comment by daniv-msft** [comment] 2020-01-10 23:22
Duplicate of https://github.com/Azure/dev-spaces/issues/260

**Closed by daniv-msft** 2020-01-10 23:22 UTC
