### ISSUE TITLE
An error occurred while creating the Space

### ISSUE THREAD

**Issue by bjbennet** [Azure/dev-spaces#116] opened 2019-06-12 22:30 UTC
Received the following error when creating a controller and dev space through VS 2019 - 

Method not found: '!!0Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject(System.String, Newtonsoft.Json.JsonConverter[])'.

![error](https://user-images.githubusercontent.com/5629450/59390700-e7dffa80-8d26-11e9-9786-fd149f6ddba9.PNG)

**Comment by YuzorMa** [comment] 2019-06-21 21:43
@bjbennet has reported that he could not reproduce this with the latest version of VS 2019.  Closing as we have not heard anyone else encounter this problem.

**Comment by cjbush** [comment] 2019-07-19 17:44
I'm experiencing this issue with the latest update to VS 2019 (16.1.6) installed. Is there something I can do to get more information as to what's causing it?

**Comment by danegsta** [comment] 2019-07-19 20:39
@cjbush this particular error message is due to a Newtonsoft.Json assembly version mismatch between the Dev Spaces tooling and Microsoft Rest library that should be resolved in the VS2019 16.2 release, which is currently in preview.

Can you try your scenario with the VS2019 preview channel release (available through the "Download Preview" link for your particular edition of Visual Studio on the [Visual Studio Downloads page](https://visualstudio.microsoft.com/downloads/)) to see if that resolves the "Method not found" error for you?

**Comment by danegsta** [comment] 2019-07-25 17:48
VS2019 version 16.2, which fixes this particular error, is now out of preview (https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.2.0).

**Closed** 2019-08-08 16:13 UTC
Labels: VS
