### ISSUE TITLE
[Local Process] VS Code Bikes Tutorial "Connect operation failed"

### ISSUE THREAD

**Issue by arkadiyan** [Azure/dev-spaces#357] opened 2020-06-17 08:19 UTC
**Describe the bug**
When following tutorial "Use Local Process with Kubernetes with Visual Studio Code (preview)" debugging "bikes" service locally fails to connect development computer to my cluster.

Dev Spaces Extension in VS Code reports following error after trying to launch with "Launch via NPM with Kubernetes (Preview)":
Failed to establish a connection. Error: Connect operation failed. Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft. For diagnostic information, see Azure Dev Spaces logs at '/var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/T/Azure Dev Spaces'.
 
**To Reproduce**
Follow "Use Local Process with Kubernetes with Visual Studio Code (preview)" from "How to" section in docs, including creation of new AKS cluster.
In VS Code debug with "Launch via NPM with Kubernetes (Preview)".

**Expected behavior**
"How to" tutorial works with VS Code, including local debugging and connecting to AKS cluster.
 
**Logs**

azds-cli-2020-06-17-07-57-04-3165.txt:

2020-06-17T07:57:04.5869270Z | CLI | TRACE | Event: Command.Start <json>{"properties":{"arguments":"prep-connect -o json"},"metrics":null}</json>\nOperation context: <json>{"clientRequestId":null,"correlationRequestId":null,"requestId":null,"userSubscriptionId":"f4a777ae-540c-4214-ac89-6806513322a7","startTime":"2020-06-17T07:57:04.2189260Z","userAgent":"VSCode/2.0.220200605","requestHttpMethod":null,"requestUri":null,"apiVersion":"3.2","version":"1.0.20200609.3","requestHeaders":{},"loggingProperties":{"applicationName":"CLI","deviceOperatingSystem":"Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64","framework":".NET Core 4.6.26515.07","macAddressHash":"8ed62ff8b3ec1bd4e9e70c39b7b3f1e84ce93f2d51ec81b3ae198f76e0d07b09","commandId":"9aa74e84-621f-41d2-add6-a471a4e307f2","processId":3165,"targetEnvironment":"Production"}}</json>
2020-06-17T07:57:07.2508730Z | CLI | TRACE | Console output (JSON):\n[]
2020-06-17T07:57:07.2542120Z | CLI | TRACE | Event: Command.End <json>{"properties":{"arguments":"prep-connect -o json","result":"Succeeded"},"metrics":{"duration":2711.0}}</json>

azds-cli-2020-06-17-07-57-08-3166.txt:

2020-06-17T07:57:08.4248590Z | CLI | TRACE | Event: Command.Start <json>{"properties":{"arguments":"connect --service bikes --env /var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/t/tmp-2877ur54jn1mebnr.env --script /var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/t/tmp-2877ur54jn1mebnr.env.cmd --control-port 51035 --ppid 2871 --elevation-requests [] --local-port 3000"},"metrics":null}</json>\nOperation context: <json>{"clientRequestId":null,"correlationRequestId":null,"requestId":null,"userSubscriptionId":"f4a777ae-540c-4214-ac89-6806513322a7","startTime":"2020-06-17T07:57:08.1203900Z","userAgent":"VSCode/2.0.220200605","requestHttpMethod":null,"requestUri":null,"apiVersion":"3.2","version":"1.0.20200609.3","requestHeaders":{},"loggingProperties":{"applicationName":"CLI","deviceOperatingSystem":"Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64","framework":".NET Core 4.6.26515.07","macAddressHash":"8ed62ff8b3ec1bd4e9e70c39b7b3f1e84ce93f2d51ec81b3ae198f76e0d07b09","commandId":"3b9874fe-c1ef-419c-8964-17c4b45711f4","processId":3166,"targetEnvironment":"Production"}}</json>
2020-06-17T07:57:09.1786080Z | CLI | TRACE | Remoting started listening on 51035
2020-06-17T07:57:11.6148380Z | CLI | TRACE | Deployment dev/bikes patched to run azds agent.\n
2020-06-17T07:57:11.6187500Z | CLI | TRACE | Found container bikes-79ccd978f4-dgwnf/bikes.\n
2020-06-17T07:57:11.6219530Z | CLI | TRACE | Connecting to dev/bikes-79ccd978f4-dgwnf...\n
2020-06-17T07:57:16.8619150Z | CLI | TRACE | Connection established.\n
2020-06-17T07:57:17.1072940Z | CLI | ERROR | Dependency: Service Run - Port Forward <json>{"target":null,"success":false,"duration":null,"properties":{"requestId":"null","clientRequestId":"null","correlationRequestId":"null"}}</json>
2020-06-17T07:57:17.1100570Z | CLI | ERROR | ServiceConnectCommand.ExecuteInnerAsync caught exception System.InvalidOperationException: System.UnauthorizedAccessException: Access to the path is denied.\n ---> System.IO.IOException: Operation not permitted\n   --- End of inner exception stack trace ---\n   at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)\n   at Interop.Sys.GetCwd()\n   at System.Environment.get_CurrentDirectory()\n   at System.IO.Directory.GetCurrentDirectory()\n   at System.Diagnostics.Process.ResolvePath(String filename)\n   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)\n   at System.Diagnostics.Process.Start()\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.KubernetesDNSManager.UpdatePF(IEnumerable`1 entries)\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.KubernetesDNSManager.UpdateRoutingTable()\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.Controllers.HostsController.<>c__DisplayClass7_0.<AllocIp>b__0()\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.Controllers.HostsController.InvokeWithExceptionHandler[T](Func`1 handler)\n   at Microsoft.Azure.DevSpaces.Common.Client.LocalConnect.KubernetesDNSManagerClient.AllocateIPAsync(IDictionary`2[] servicePortsList, CancellationToken cancellationToken) in E:\A\_work\1178\s\src\common.client\LocalConnect\KubernetesDNSManagerClient.cs:line 63\n   at Microsoft.Azure.DevSpaces.Client.LocalConnect.WorkloadEnvService.StartServiceRoutersAsync(ContainerWorkloadInfo workloadInfo, IEnumerable`1 elevationRequests, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\1178\s\src\client\LocalConnect\WorkloadEnvService.cs:line 117\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ConnectManagementClient.<>c__DisplayClass14_0.<<ConfigureLocalHostAsync>b__0>d.MoveNext() in E:\A\_work\1178\s\src\client\Client\ManagementClients\ConnectManagementClient.cs:line 227\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.DevSpacesManagementClientExceptionStrategy.RunWithHandlingAsync[T](Func`1 func, FailureConfig failureConfig) in E:\A\_work\1178\s\src\client\Client\ManagementClients\ExceptionStrategies\DevSpacesManagementClientExceptionStrategy.cs:line 57\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ConnectManagementClient.ConfigureLocalHostAsync(ContainerWorkloadInfo containerWorkloadInfo, Int32[] localPorts, IEnumerable`1 elevationRequests, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\1178\s\src\client\Client\ManagementClients\ConnectManagementClient.cs:line 213\n   at Microsoft.Azure.DevSpaces.Cli.Commands.Connect.ConnectCommand.RunWorkloadAsync(ContainerWorkloadInfo containerWorkloadInfo, IConnectManagementClient connectManagementClient, IEnumerable`1 elevationRequests, CancellationToken cancellationToken) in E:\A\_work\1178\s\src\cli\Commands\Connect\ConnectCommand.cs:line 636\n   at Microsoft.Azure.DevSpaces.Cli.Commands.Connect.ConnectCommand.ExecuteInnerAsync(IConnectManagementClient connectManagementClient, Action`1 workloadStartedHandler, CancellationToken cancellationToken) in E:\A\_work\1178\s\src\cli\Commands\Connect\ConnectCommand.cs:line 474
2020-06-17T07:57:17.1103770Z | CLI | ERROR | Connect operation failed.\n
2020-06-17T07:57:17.1105460Z | CLI | TRACE | Stopping workload and cleaning up...\n
2020-06-17T07:57:17.2517060Z | CLI | TRACE | Restore: Deployment 'bikes' restored to original state.\n
2020-06-17T07:57:17.2575180Z | CLI | ERROR | Dependency: Service Run - Port Forward <json>{"target":null,"success":false,"duration":null,"properties":{"requestId":"null","clientRequestId":"null","correlationRequestId":"null"}}</json>
2020-06-17T07:57:17.2607190Z | CLI | ERROR | Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.\nFor diagnostic information, see Azure Dev Spaces logs at '/var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/T/Azure Dev Spaces'.\n
2020-06-17T07:57:17.2642450Z | CLI | ERROR | Logging handled exception: System.InvalidOperationException: {"ClassName":"System.InvalidOperationException","Message":"System.UnauthorizedAccessException: Access to the path is denied.\n ---> System.IO.IOException: Operation not permitted\n   --- End of inner exception stack trace ---\n   at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)\n   at Interop.Sys.GetCwd()\n   at System.Environment.get_CurrentDirectory()\n   at System.IO.Directory.GetCurrentDirectory()\n   at System.Diagnostics.Process.ResolvePath(String filename)\n   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)\n   at System.Diagnostics.Process.Start()\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.KubernetesDNSManager.UpdatePF(IEnumerable`1 entries)\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.KubernetesDNSManager.UpdateRoutingTable()\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.Controllers.HostsController.<>c__DisplayClass7_0.<AllocIp>b__0()\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.Controllers.HostsController.InvokeWithExceptionHandler[T](Func`1 handler)","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.Azure.DevSpaces.Common.Client.LocalConnect.KubernetesDNSManagerClient.AllocateIPAsync(IDictionary`2[] servicePortsList, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\common.client\\LocalConnect\\KubernetesDNSManagerClient.cs:line 63\n   at Microsoft.Azure.DevSpaces.Client.LocalConnect.WorkloadEnvService.StartServiceRoutersAsync(ContainerWorkloadInfo workloadInfo, IEnumerable`1 elevationRequests, IProgress`1 progress, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\client\\LocalConnect\\WorkloadEnvService.cs:line 117\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ConnectManagementClient.<>c__DisplayClass14_0.<<ConfigureLocalHostAsync>b__0>d.MoveNext() in E:\\A\\_work\\1178\\s\\src\\client\\Client\\ManagementClients\\ConnectManagementClient.cs:line 227\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.DevSpacesManagementClientExceptionStrategy.RunWithHandlingAsync[T](Func`1 func, FailureConfig failureConfig) in E:\\A\\_work\\1178\\s\\src\\client\\Client\\ManagementClients\\ExceptionStrategies\\DevSpacesManagementClientExceptionStrategy.cs:line 57\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ConnectManagementClient.ConfigureLocalHostAsync(ContainerWorkloadInfo containerWorkloadInfo, Int32[] localPorts, IEnumerable`1 elevationRequests, IProgress`1 progress, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\client\\Client\\ManagementClients\\ConnectManagementClient.cs:line 213\n   at Microsoft.Azure.DevSpaces.Cli.Commands.Connect.ConnectCommand.RunWorkloadAsync(ContainerWorkloadInfo containerWorkloadInfo, IConnectManagementClient connectManagementClient, IEnumerable`1 elevationRequests, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\cli\\Commands\\Connect\\ConnectCommand.cs:line 636\n   at Microsoft.Azure.DevSpaces.Cli.Commands.Connect.ConnectCommand.ExecuteInnerAsync(IConnectManagementClient connectManagementClient, Action`1 workloadStartedHandler, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\cli\\Commands\\Connect\\ConnectCommand.cs:line 474\n   at Microsoft.Azure.DevSpaces.Cli.Commands.Connect.ConnectCommand.ExecuteInnerAsync(IConnectManagementClient connectManagementClient, Action`1 workloadStartedHandler, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\cli\\Commands\\Connect\\ConnectCommand.cs:line 528\n   at Microsoft.Azure.DevSpaces.Cli.Commands.Connect.ConnectCommand.ExecuteAsync() in E:\\A\\_work\\1178\\s\\src\\cli\\Commands\\Connect\\ConnectCommand.cs:line 406\n   at Microsoft.Azure.DevSpaces.Cli.DevSpacesCliApp.RunCommandAsync(String[] args, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\cli\\DevSpacesCliApp.cs:line 190\n   at Microsoft.Azure.DevSpaces.Cli.DevSpacesCliApp.ExecuteAsync(String[] args, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\cli\\DevSpacesCliApp.cs:line 149","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"Microsoft.Azure.DevSpaces.Common.Client","WatsonBuckets":null}
2020-06-17T07:57:17.2664920Z | CLI | TRACE | Event: Command.End <json>{"properties":{"arguments":"connect --service bikes --env /var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/t/tmp-2877ur54jn1mebnr.env --script /var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/t/tmp-2877ur54jn1mebnr.env.cmd --control-port 51035 --ppid 2871 --elevation-requests [] --local-port 3000","result":"Failed"},"metrics":{"duration":8882.0}}</json>

azds-cli-2020-06-17-08-00-39-3197.txt:

2020-06-17T08:00:39.5697720Z | CLI | TRACE | Event: Command.Start <json>{"properties":{"arguments":"--version"},"metrics":null}</json>\nOperation context: <json>{"clientRequestId":null,"correlationRequestId":null,"requestId":null,"userSubscriptionId":"f4a777ae-540c-4214-ac89-6806513322a7","startTime":"2020-06-17T08:00:39.2716540Z","userAgent":"CLI/1.0.20200609.3","requestHttpMethod":null,"requestUri":null,"apiVersion":"3.2","version":"1.0.20200609.3","requestHeaders":{},"loggingProperties":{"applicationName":"CLI","deviceOperatingSystem":"Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64","framework":".NET Core 4.6.26515.07","macAddressHash":"8ed62ff8b3ec1bd4e9e70c39b7b3f1e84ce93f2d51ec81b3ae198f76e0d07b09","commandId":"d16b434d-8574-4bea-a6b2-d79b59f85ba8","processId":3197,"targetEnvironment":"Production"}}</json>

azds-sdk-2020-06-17-07-57-04-3165.txt:

2020-06-17T07:57:07.2215530Z | SDK | TRACE | Event: LocalConnect-GetReachableServices <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":2018.0}}</json>\nOperation context: <json>{"clientRequestId":null,"correlationRequestId":null,"requestId":null,"userSubscriptionId":null,"startTime":"2020-06-17T07:57:04.6812290Z","userAgent":"VSCode/2.0.220200605","requestHttpMethod":null,"requestUri":null,"apiVersion":"3.2","version":"1.0.20200609.3","requestHeaders":{},"loggingProperties":{"applicationName":"SDK","deviceOperatingSystem":"Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64","framework":".NET Core 4.6.26515.07","macAddressHash":"8ed62ff8b3ec1bd4e9e70c39b7b3f1e84ce93f2d51ec81b3ae198f76e0d07b09","processId":3165,"targetEnvironment":"Production"}}</json>
2020-06-17T07:57:07.2410920Z | SDK | TRACE | Event: ConnectManagementClient-GetElevationRequests <json>{"properties":{"result":"[]","result":"Succeeded"},"metrics":{"duration":2064.0}}</json>

azds-sdk-2020-06-17-07-57-08-3166.txt:

2020-06-17T07:57:10.2833910Z | SDK | TRACE | Event: LocalConnect-GetPodAndContainerFromService <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":821.0}}</json>\nOperation context: <json>{"clientRequestId":null,"correlationRequestId":null,"requestId":null,"userSubscriptionId":null,"startTime":"2020-06-17T07:57:08.4927610Z","userAgent":"VSCode/2.0.220200605","requestHttpMethod":null,"requestUri":null,"apiVersion":"3.2","version":"1.0.20200609.3","requestHeaders":{},"loggingProperties":{"applicationName":"SDK","deviceOperatingSystem":"Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64","framework":".NET Core 4.6.26515.07","macAddressHash":"8ed62ff8b3ec1bd4e9e70c39b7b3f1e84ce93f2d51ec81b3ae198f76e0d07b09","processId":3166,"targetEnvironment":"Production"}}</json>
2020-06-17T07:57:10.5956170Z | SDK | TRACE | Event: ContainerPatchService-FindDeployment <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":304.0}}</json>
2020-06-17T07:57:10.5973170Z | SDK | TRACE | Event: LocalConnect-GetDeploymentFromPodIdentifier <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":309.0}}</json>
2020-06-17T07:57:10.6921200Z | SDK | TRACE | Event: LocalConnect-VerifyAksCluster <json>{"properties":{"isAksCluster":"true","region":"","azdsEnabled":"false","result":"Succeeded"},"metrics":{"duration":86.0}}</json>
2020-06-17T07:57:11.0909880Z | SDK | TRACE | Deployment patch created: True
2020-06-17T07:57:11.6155930Z | SDK | TRACE | Event: ContainerPatchService-PatchDeployment <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":911.0}}</json>
2020-06-17T07:57:11.7175990Z | SDK | TRACE | ForwardDevHostAgent uses port 51506
2020-06-17T07:57:11.7213750Z | SDK | TRACE | Invoking kubectl Exec command: exec -t bikes-79ccd978f4-dgwnf -c bikes -n dev -- sh -c "/.azds-agent/azds-agent.sh run"
2020-06-17T07:57:11.7323420Z | SDK | TRACE | Invoked long running kubectl Exec command: 'exec -t bikes-79ccd978f4-dgwnf -c bikes -n dev -- sh -c "/.azds-agent/azds-agent.sh run"'
2020-06-17T07:57:14.9274200Z | SDK | TRACE | Reset completed
2020-06-17T07:57:15.4366080Z | SDK | TRACE | Dependency: Kubernetes <json>{"target":"Exec","success":true,"duration":null,"properties":{"targetCluster":"user cluster","error":"command terminated with exit code 1","exitCode":"0"}}</json>
2020-06-17T07:57:16.8317870Z | SDK | TRACE | Event: LocalConnect-GetReachableServices <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":1536.0}}</json>
2020-06-17T07:57:16.8585930Z | SDK | TRACE | Event: LocalConnect-StartRemoteAgent <json>{"properties":{"containerIdOption":"Deployment","hasLocalProcessConfig":"false","containerIdentifier":"true","result":"Succeeded"},"metrics":{"duration":6255.0}}</json>
2020-06-17T07:57:16.8590930Z | SDK | TRACE | Event: ConnectManagementClient-StartRemoteAgent <json>{"properties":{"containerConnectionMode":"2","sourceK8sEntityType":"1","sourceNamespaceName":"dev","targetNamespaceName":"","sourceK8sEntityName":"bikes","sourceContainerName":"bikes","localProcessConfigFilePath":"KubernetesLocalProcessConfig.yaml","result":"Succeeded"},"metrics":{"duration":7415.0}}</json>
2020-06-17T07:57:17.0117360Z | SDK | TRACE | Event: WorkloadEnvService-StartServiceRouters <json>{"properties":{"result":"Failed"},"metrics":{"duration":137.0}}</json>\nOperation context: <json>{"clientRequestId":null,"correlationRequestId":null,"requestId":null,"userSubscriptionId":null,"startTime":"2020-06-17T07:57:08.4927610Z","userAgent":null,"requestHttpMethod":null,"requestUri":null,"apiVersion":"3.2","version":"1.0.20200609.3","requestHeaders":{},"loggingProperties":{"applicationName":"SDK","deviceOperatingSystem":"Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64","framework":".NET Core 4.6.26515.07","macAddressHash":"8ed62ff8b3ec1bd4e9e70c39b7b3f1e84ce93f2d51ec81b3ae198f76e0d07b09","processId":3166,"targetEnvironment":"Production"}}</json>
2020-06-17T07:57:17.0127090Z | SDK | TRACE | Event: ConnectManagementClient-ConfigureLocalHost <json>{"properties":{"container":"93253ae00ba9","numOfReachableServices":"11","numOfEnvironmentVariables":"11","numOfContainerPorts":"1","numOfVolumeMounts":"1","result":"Failed"},"metrics":{"duration":143.0}}</json>
2020-06-17T07:57:17.0135350Z | SDK | ERROR | Failed to configure local host.
2020-06-17T07:57:17.0926390Z | SDK | ERROR | Logging handled exception: System.InvalidOperationException: {"ClassName":"System.InvalidOperationException","Message":"System.UnauthorizedAccessException: Access to the path is denied.\n ---> System.IO.IOException: Operation not permitted\n   --- End of inner exception stack trace ---\n   at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)\n   at Interop.Sys.GetCwd()\n   at System.Environment.get_CurrentDirectory()\n   at System.IO.Directory.GetCurrentDirectory()\n   at System.Diagnostics.Process.ResolvePath(String filename)\n   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)\n   at System.Diagnostics.Process.Start()\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.KubernetesDNSManager.UpdatePF(IEnumerable`1 entries)\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.KubernetesDNSManager.UpdateRoutingTable()\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.Controllers.HostsController.<>c__DisplayClass7_0.<AllocIp>b__0()\n   at Microsoft.Azure.DevSpaces.KubernetesDNSManager.Controllers.HostsController.InvokeWithExceptionHandler[T](Func`1 handler)","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.Azure.DevSpaces.Common.Client.LocalConnect.KubernetesDNSManagerClient.AllocateIPAsync(IDictionary`2[] servicePortsList, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\common.client\\LocalConnect\\KubernetesDNSManagerClient.cs:line 63\n   at Microsoft.Azure.DevSpaces.Client.LocalConnect.WorkloadEnvService.StartServiceRoutersAsync(ContainerWorkloadInfo workloadInfo, IEnumerable`1 elevationRequests, IProgress`1 progress, CancellationToken cancellationToken) in E:\\A\\_work\\1178\\s\\src\\client\\LocalConnect\\WorkloadEnvService.cs:line 117\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ConnectManagementClient.<>c__DisplayClass14_0.<<ConfigureLocalHostAsync>b__0>d.MoveNext() in E:\\A\\_work\\1178\\s\\src\\client\\Client\\ManagementClients\\ConnectManagementClient.cs:line 227\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.DevSpacesManagementClientExceptionStrategy.RunWithHandlingAsync[T](Func`1 func, FailureConfig failureConfig) in E:\\A\\_work\\1178\\s\\src\\client\\Client\\ManagementClients\\ExceptionStrategies\\DevSpacesManagementClientExceptionStrategy.cs:line 57","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"Microsoft.Azure.DevSpaces.Common.Client","WatsonBuckets":null}
2020-06-17T07:57:17.1266600Z | SDK | TRACE | Event: WorkloadEnvService-StopWorkload <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":0.0}}</json>
2020-06-17T07:57:17.1269880Z | SDK | TRACE | Event: ConnectManagementClient-ResetLocalConnection <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":1.0}}</json>
2020-06-17T07:57:17.2519750Z | SDK | TRACE | Event: ContainerPatchService-Restore <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":132.0}}</json>
2020-06-17T07:57:17.2529750Z | SDK | TRACE | Event: LocalConnect-RestoreRemoteAgent <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":138.0}}</json>
2020-06-17T07:57:17.2540160Z | SDK | TRACE | Event: ConnectManagementClient-RestoreOriginalRemoteContainer <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":140.0}}</json>
2020-06-17T07:57:17.2558870Z | SDK | TRACE | Event: WorkloadContainerEnvService-StopWorkloadContainer <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":0.0}}</json>
2020-06-17T07:57:17.2561040Z | SDK | TRACE | Event: ConnectManagementClient-StopContainerizedWorkload <json>{"properties":{"result":"Succeeded"},"metrics":{"duration":0.0}}</json>
 
**Environment Details**
Client used (CLI/VS Code/Visual Studio): VS Code

CLI:     
Azure Dev Spaces CLI
1.0.20200609.3
API v3.2

VS Code: 
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
Azure Dev Spaces: v2.0.220200605
Azure Kubernetes Service: v0.0.6

Operating System: macOS 10.15.5
 
**Additional context**
VS Code output:

Local KubernetesDNSManager started on port 50052.
lo0 alias 127.1.1.1 netmask 255.255.255.255
lo0 alias 127.1.1.2 netmask 255.255.255.255
lo0 alias 127.1.1.3 netmask 255.255.255.255
lo0 alias 127.1.1.4 netmask 255.255.255.255
lo0 alias 127.1.1.5 netmask 255.255.255.255
lo0 alias 127.1.1.6 netmask 255.255.255.255
lo0 alias 127.1.1.7 netmask 255.255.255.255
lo0 alias 127.1.1.8 netmask 255.255.255.255
lo0 alias 127.1.1.9 netmask 255.255.255.255
lo0 alias 127.1.1.10 netmask 255.255.255.255
lo0 alias 127.1.1.11 netmask 255.255.255.255
Idle timeout reached, terminate.
Hello
lo0 -alias 127.1.1.1
lo0 -alias 127.1.1.2
[
  {
    "requestType": "EditHostsFile"
  }
]Deployment dev/bikes patched to run azds agent.
Deployment dev/bikes patched to run azds agent.
Found container bikes-79ccd978f4-9fdnx/bikes.
Found container bikes-79ccd978f4-9fdnx/bikes.
Connecting to dev/bikes-79ccd978f4-9fdnx...
Connecting to dev/bikes-79ccd978f4-9fdnx...
Connection established.
Connection established.
Launch KubernetesDNSManager: osascript -e "do shell script \"exec \\\"/Users/arkadiya/lib/azds-cli/KubernetesDNSManager\\\"\" with administrator privileges"
Launch KubernetesDNSManager: osascript -e "do shell script \"exec \\\"/Users/arkadiya/lib/azds-cli/KubernetesDNSManager\\\"\" with administrator privileges"
Connect operation failed.
Connect operation failed.
Stopping workload and cleaning up...
Stopping workload and cleaning up...
Restore: Deployment 'bikes' restored to original state.
Restore: Deployment 'bikes' restored to original state.
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at '/var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/T/Azure Dev Spaces'.
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at '/var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/T/Azure Dev Spaces'.
Failed to establish a connection. Error: Connect operation failed.
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at '/var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/T/Azure Dev Spaces'.

[][]Deployment dev/bikes patched to run azds agent.
Deployment dev/bikes patched to run azds agent.
Deployment dev/bikes patched to run azds agent.
Found container bikes-79ccd978f4-dgwnf/bikes.
Found container bikes-79ccd978f4-dgwnf/bikes.
Found container bikes-79ccd978f4-dgwnf/bikes.
Connecting to dev/bikes-79ccd978f4-dgwnf...
Connecting to dev/bikes-79ccd978f4-dgwnf...
Connecting to dev/bikes-79ccd978f4-dgwnf...
Connection established.
Connection established.
Connection established.
Connect operation failed.
Connect operation failed.
Connect operation failed.
Stopping workload and cleaning up...
Stopping workload and cleaning up...
Stopping workload and cleaning up...
Restore: Deployment 'bikes' restored to original state.
Restore: Deployment 'bikes' restored to original state.
Restore: Deployment 'bikes' restored to original state.
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at '/var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/T/Azure Dev Spaces'.
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at '/var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/T/Azure Dev Spaces'.
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at '/var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/T/Azure Dev Spaces'.
Failed to establish a connection. Error: Connect operation failed.
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at '/var/folders/19/mk67cjtd32gbvlqdv0k_t_v40000gn/T/Azure Dev Spaces'.

**Comment by daniv-msft** [comment] 2020-06-18 01:43
Thank you for reporting this issue, and sorry you encountered it.
This bug was already reported by another customer a couple of days ago, but we couldn't find the root cause so far. However, the logs you shared are quite interesting because they showed something we didn't see before:
```
Launch KubernetesDNSManager: osascript -e "do shell script "exec \"/Users/arkadiya/lib/azds-cli/KubernetesDNSManager\"" with administrator privileges"
```

We're investigating this bug, and we'll update this issue once we have an update.

**Comment by arkadiyan** [comment] 2020-07-09 17:51
I tried starting VS Code with elevated rights:
sudo open '/Applications/Visual Studio Code.app'

It fails with exact same permission issue as before:
"System.UnauthorizedAccessException: Access to the path is denied"

**Comment by amsoedal** [comment] 2020-07-09 18:42
Hi @arkadiyan, thanks for following up. Sorry for the slowness on our end.  I think this issue is happening because our tools don't have permission to resolve the current working directory when trying to execute pfctl on the command line.  We're working on a solution that will hopefully avoid using pfctl altogether, although I have an idea for a possible workaround in the meantime -- can we connect on email? ansoedal@microsoft.com

**Comment by philon-msft** [comment] 2020-07-10 21:32
We've released a new build of the Dev Spaces CLI that contains a fix for this issue. To install the new build, download and run the appropriate installer listed here: https://aka.ms/azds-tools-missing
Please let us know if this doesn't resolve the issue for you.

**Closed by philon-msft** 2020-07-10 21:32 UTC
