### ISSUE TITLE
Port forwarding not working

### ISSUE THREAD

**Issue by jdharmon** [Azure/dev-spaces#130] opened 2019-07-10 19:14 UTC
If I start a project either with Visual Studio or ```azds up```, the container builds successfully, I see the following message, but I am not able to connect to the service at http://localhost:54589.

```
Service 'failurecode-api' port 80 (http) is available via port forwarding at http://localhost:54589
```

Using ```kubectl port-forward``` works fine. I am able to connect to my service on http://localhost:55555:

```
kubectl port-forward -n jason service/failurecode-api 55555:80
Forwarding from 127.0.0.1:55555 -> 80
Forwarding from [::1]:55555 -> 80
```

**Comment by sanar-microsoft** [comment] 2019-07-10 23:51
@jdharmon Do you consistently hit this issue this? On AKS the port forwarding uses tunnelfront pod in the kube-system namespace and it is possible that a transient issue there caused this error. If this is a consistent repro, can you share the controller information for further investigation?

**Comment by jdharmon** [comment] 2019-07-11 00:41
The issue is consistent on machines behind a corporate firewall. Which ports should I request be opened for tunnelfront?

**Comment by sanar-microsoft** [comment] 2019-07-11 16:18
You don't have to do that, it is AKS's API server that uses tunnelfront for long running connections like port forwarding. Can you also try one more thing? Are you able to manually use port 54589 for port forwarding using kubectl?

**Comment by jdharmon** [comment] 2019-07-11 18:06
Manually forwarding to 54589 does work.

```
kubectl port-forward -n jason service/failurecode-api 54589:80
Forwarding from 127.0.0.1:54589 -> 80
Forwarding from [::1]:54589 -> 80
Handling connection for 54589
```

```
curl -v http://localhost:54589/api/applications
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 54589 (#0)
> GET /api/applications HTTP/1.1
> Host: localhost:54589
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 11 Jul 2019 18:01:08 GMT
< Content-Type: application/json; charset=utf-8
< Server: Kestrel
< Transfer-Encoding: chunked
<
```

**Comment by sanar-microsoft** [comment] 2019-07-11 18:34
Can you run `azds up -v`? This will generate verbose logs on the console. Do you see any error on the console? Also can you share the controller information? You can get that information by running `azds controller list -v`.

**Comment by jdharmon** [comment] 2019-07-11 20:18
Here is the output from both commands:
```
> azds controller list -v
Azure Dev Spaces Controllers in subscription '93bd6626-b3db-44e6-bad4-95803fc8ec51':
   Name                ResourceGroup    Location  ProvisioningState
-  ------------------  ---------------  --------  -----------------
*  web-aks-stihldev-d  STIHLDev-D-USEA  eastus2   Succeeded
```

```
> azds up -v
Using dev space 'jason' with target 'web-aks-stihldev-d'
Synchronizing files...2s
Installing Helm chart...
Release "azds-e348e2-jason-failurecode-api" has been upgraded. Happy Helming!
LAST DEPLOYED: Thu Jul 11 20:10:55 2019
NAMESPACE: jason
STATUS: DEPLOYED
RESOURCES:
==> v1/Pod(related)
NAME                             READY  STATUS   RESTARTS  AGE
failurecode-api-cbd4c5574-xgldc  2/2    Running  0         123m
==> v1/Service
NAME             TYPE       CLUSTER-IP   EXTERNAL-IP  PORT(S)  AGE
failurecode-api  ClusterIP  10.0.155.77  <none>       80/TCP   132m
==> v1beta2/Deployment
NAME             READY  UP-TO-DATE  AVAILABLE  AGE
failurecode-api  1/1    0           1          132m
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace jason -l "app=failurecode-api,release=azds-e348e2-jason-failurecode-api" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
Installed chart in 2s
Waiting for container image build...5s
Building container image...
Sending build context to Docker daemon  7.994MB
Step 1/14 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2
---> 52c7fe591881
Step 2/14 : ARG BUILD_CONFIGURATION=Debug
---> Using cache
---> 37313ac11d25
Step 3/14 : ENV ASPNETCORE_ENVIRONMENT=Development
---> Using cache
---> 2a6b7afc2e95
Step 4/14 : ENV DOTNET_USE_POLLING_FILE_WATCHER=true
---> Using cache
---> 9026443d6c8f
Step 5/14 : EXPOSE 80
---> Using cache
---> 08681a18ec26
Step 6/14 : WORKDIR /src
---> Using cache
---> 02b16af5af7c
Step 7/14 : COPY ["FailureCode.Api/FailureCode.Api.csproj", "FailureCode.Api/"]
---> Using cache
---> 91eb0b871f31
Step 8/14 : COPY ["FailureCode.Data/FailureCode.Data.csproj", "FailureCode.Data/"]
---> Using cache
---> 8b7a0da1cb4c
Step 9/14 : RUN dotnet restore "FailureCode.Api/FailureCode.Api.csproj"
---> Using cache
---> 12fca4174c4e
Step 10/14 : COPY . .
---> Using cache
---> 701621f4f3e1
Step 11/14 : WORKDIR "/src/FailureCode.Api"
---> Using cache
---> b7c5e007ed3e
Step 12/14 : RUN dotnet build --no-restore "FailureCode.Api.csproj" -c $BUILD_CONFIGURATION
---> Using cache
---> 993423b10b0a
Step 13/14 : RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh
---> Using cache
---> 9ba996e41323
Step 14/14 : ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
---> Using cache
---> af41ff41454a
Successfully built af41ff41454a
Successfully tagged failurecode-api:devspaces-x016be2a8ff3415e8
Built container image in 1s
Waiting for container...2s
Service 'failurecode-api' port 80 (http) is available via port forwarding at http://localhost:54589
press Ctrl+C to detach
failurecode-api-9bb699647-29hkb: : Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
failurecode-api-9bb699647-29hkb:       User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
failurecode-api-9bb699647-29hkb: ←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
failurecode-api-9bb699647-29hkb:       Creating key {6a7a3905-e08f-4cac-aa5a-260340faa92c} with creation date 2019-07-11 20:11:06Z, activation date 2019-07-11 20:11:06Z, and expiration date 2019-10-09 20:11:06Z.
failurecode-api-9bb699647-29hkb: ←[40m←[1m←[33mwarn←[39m←[22m←[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
failurecode-api-9bb699647-29hkb:       No XML encryptor configured. Key {6a7a3905-e08f-4cac-aa5a-260340faa92c} may be persisted to storage in unencrypted form.
failurecode-api-9bb699647-29hkb: ←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
failurecode-api-9bb699647-29hkb:       Writing data to file '/root/.aspnet/DataProtection-Keys/key-6a7a3905-e08f-4cac-aa5a-260340faa92c.xml'.
failurecode-api-9bb699647-29hkb: Hosting environment: Development
failurecode-api-9bb699647-29hkb: Content root path: /src/FailureCode.Api
failurecode-api-9bb699647-29hkb: Now listening on: http://[::]:80
failurecode-api-9bb699647-29hkb: Application started. Press Ctrl+C to shut down.
```

**Comment by xinyanmsft** [comment] 2019-07-12 04:32
@jdharmon, you said "The issue is consistent on machines behind the corporate firewall". What kind of corporate firewall do you have?

**Comment by jdharmon** [comment] 2019-07-12 13:28
We're using a Check Point firewall. I was initially unable to enable Dev Spaces or use kubectl because of HTTPS inspection. After inspection was disabled, everything seems to be working except the forwarded ports.

**Comment by xinyanmsft** [comment] 2019-07-13 06:04
[portforward-tester.zip](https://github.com/Azure/dev-spaces/files/3388499/portforward-tester.zip)
@jdharmon, I built a 'port forward tester' program. can you try this on your machine, and send me back the log it captured?
Take this zip file, unzip to your local machine, and open the solution in Visual Studio. The startup project should be 'portforward-tester'. Run this program, enter the namespace (such as 'kube-system'), pod name (such as kubernetes-dashboard-574465bdbd-vs29t), container port (such as 9090) and click 'start port forwarding' button. Then try to access the local port. The logs contains diagnostics information of what happened and where the failure should be. Please send the error log to me (xinyan@microsoft.com). 
The code is basically a simple WinForm application, with a slightly modified Kubernetes c# client (https://github.com/kubernetes-client/csharp) with extra logging.
thanks very much for your help!

**Comment by jdharmon** [comment] 2019-07-13 14:24
@xinyanmsft Thank you. I will run the tester Monday morning.

**Comment by xinyanmsft** [comment] 2019-07-17 19:23
after investigation, this seems to be a system limitation on Windows Server 2012 R2. I've created bug https://github.com/kubernetes-client/csharp/issues/290.

**Comment by YuzorMa** [comment] 2019-07-19 18:45
Dev Spaces does not fully support Windows Server 2012 R2 (or Windows 7) and we will update out installer to block earlier.  Closing out the issue.

**Closed by YuzorMa** 2019-07-19 18:45 UTC
