### ISSUE TITLE
Devspace-build crashes

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#154] opened 2019-09-05 07:32 UTC
Today I started to have a problem with a pod being stuck at initializing when we tried to build it using VS 2019 and Dev Spaces.

After som digging I found that the devspace-build container throws a error and halts, leaving the build in limbo. VS was telling me that it was still building.

This is the error log from the devspace-build container:

> "2019-09-05T07:16:26.7867482Z" : Download workspace(version=1.0.20190829.2)(clientRequestId=20c87aa0-4fa1-4ab1-be5d-de66978cae31)(correlationRequestId=1bec58f8-bf78-43fa-8c0b-bfe6b5ce3ca2)(ApplicationName=BuildService)(DeviceOperatingSystem=Linux 4.15.0-1052-azure #57-Ubuntu SMP Tue Jul 23 19:07:16 UTC 2019)(Framework=.NET Core 4.6.27817.01)
> "2019-09-05T07:16:26.8569567Z" : Log Handler started(version=1.0.20190829.2)(clientRequestId=20c87aa0-4fa1-4ab1-be5d-de66978cae31)(correlationRequestId=1bec58f8-bf78-43fa-8c0b-bfe6b5ce3ca2)(ApplicationName=BuildService)(DeviceOperatingSystem=Linux 4.15.0-1052-azure #57-Ubuntu SMP Tue Jul 23 19:07:16 UTC 2019)(Framework=.NET Core 4.6.27817.01)
> "2019-09-05T07:18:06.9804378Z" : WARNING: DownloadWorkspaceAsync failed with {"ClassName":"System.Threading.Tasks.TaskCanceledException","Message":"The operation was canceled.","Data":null,"InnerException":{"ClassName":"System.IO.IOException","Message":"The server returned an invalid or unrecognized response.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.Http.HttpConnection.FillAsync()\n   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)\n   at System.Threading.Tasks.ValueTask`1.get_Result()\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232800,"Source":"System.Net.Http","WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at Microsoft.Azure.DevSpaces.Common.Auth.Handlers.AuthErrorHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /app/common.auth/Handlers/AuthErrorHttpHandler.cs:line 47\n   at Microsoft.Azure.DevSpaces.Common.Auth.Handlers.ServiceClientCredentialsHttpHandler`1.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /app/common.auth/Handlers/ServiceClientCredentialsHttpHandler.cs:line 34\n   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Microsoft.Azure.DevSpaces.ExecService.Client.WorkspaceOperations.DownloadSourceWithHttpMessagesAsync(String spaceName, String serviceName, String name, Dictionary`2 customHeaders, CancellationToken cancellationToken) in /app/execsvc.client.autogen/WorkspaceOperations.cs:line 161\n   at Microsoft.Azure.DevSpaces.ExecService.Client.WorkspaceOperationsExtensions.DownloadSourceAsync(IWorkspaceOperations operations, String spaceName, String serviceName, String name, CancellationToken cancellationToken) in /app/execsvc.client.autogen/WorkspaceOperationsExtensions.cs:line 49\n   at Microsoft.Azure.DevSpaces.Build.BuildClient.DownloadWorkspaceAsync() in /app/build/BuildClient.cs:line 113","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233029,"Source":"Microsoft.Rest.ClientRuntime","WatsonBuckets":null}, retry.(version=1.0.20190829.2)(clientRequestId=20c87aa0-4fa1-4ab1-be5d-de66978cae31)(correlationRequestId=1bec58f8-bf78-43fa-8c0b-bfe6b5ce3ca2)(ApplicationName=BuildService)(DeviceOperatingSystem=Linux 4.15.0-1052-azure #57-Ubuntu SMP Tue Jul 23 19:07:16 UTC 2019)(Framework=.NET Core 4.6.27817.01)
> "2019-09-05T07:19:47.5099688Z" : WARNING: DownloadWorkspaceAsync failed with {"ClassName":"System.Threading.Tasks.TaskCanceledException","Message":"The operation was canceled.","Data":null,"InnerException":{"ClassName":"System.IO.IOException","Message":"Unable to read data from the transport connection: Operation canceled.","Data":null,"InnerException":{"ClassName":"System.Net.Sockets.SocketException","Message":"Operation canceled","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":null,"RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467259,"Source":null,"WatsonBuckets":null,"NativeErrorCode":125},"HelpURL":null,"StackTraceString":"   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)\n   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)\n   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)\n   at System.Net.Http.HttpConnection.FillAsync()\n   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)\n   at System.Threading.Tasks.ValueTask`1.get_Result()\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232800,"Source":"System.Net.Sockets","WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at Microsoft.Azure.DevSpaces.Common.Auth.Handlers.AuthErrorHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /app/common.auth/Handlers/AuthErrorHttpHandler.cs:line 47\n   at Microsoft.Azure.DevSpaces.Common.Auth.Handlers.ServiceClientCredentialsHttpHandler`1.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /app/common.auth/Handlers/ServiceClientCredentialsHttpHandler.cs:line 34\n   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Microsoft.Azure.DevSpaces.ExecService.Client.WorkspaceOperations.DownloadSourceWithHttpMessagesAsync(String spaceName, String serviceName, String name, Dictionary`2 customHeaders, CancellationToken cancellationToken) in /app/execsvc.client.autogen/WorkspaceOperations.cs:line 161\n   at Microsoft.Azure.DevSpaces.ExecService.Client.WorkspaceOperationsExtensions.DownloadSourceAsync(IWorkspaceOperations operations, String spaceName, String serviceName, String name, CancellationToken cancellationToken) in /app/execsvc.client.autogen/WorkspaceOperationsExtensions.cs:line 49\n   at Microsoft.Azure.DevSpaces.Build.BuildClient.DownloadWorkspaceAsync() in /app/build/BuildClient.cs:line 113","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233029,"Source":"Microsoft.Rest.ClientRuntime","WatsonBuckets":null}, retry.(version=1.0.20190829.2)(clientRequestId=20c87aa0-4fa1-4ab1-be5d-de66978cae31)(correlationRequestId=1bec58f8-bf78-43fa-8c0b-bfe6b5ce3ca2)(ApplicationName=BuildService)(DeviceOperatingSystem=Linux 4.15.0-1052-azure #57-Ubuntu SMP Tue Jul 23 19:07:16 UTC 2019)(Framework=.NET Core 4.6.27817.01)
> "2019-09-05T07:21:28.0317373Z" : WARNING: DownloadWorkspaceAsync failed with {"ClassName":"System.Threading.Tasks.TaskCanceledException","Message":"The operation was canceled.","Data":null,"InnerException":{"ClassName":"System.IO.IOException","Message":"The server returned an invalid or unrecognized response.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.Http.HttpConnection.FillAsync()\n   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)\n   at System.Threading.Tasks.ValueTask`1.get_Result()\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232800,"Source":"System.Net.Http","WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at Microsoft.Azure.DevSpaces.Common.Auth.Handlers.AuthErrorHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /app/common.auth/Handlers/AuthErrorHttpHandler.cs:line 47\n   at Microsoft.Azure.DevSpaces.Common.Auth.Handlers.ServiceClientCredentialsHttpHandler`1.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /app/common.auth/Handlers/ServiceClientCredentialsHttpHandler.cs:line 34\n   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Microsoft.Azure.DevSpaces.ExecService.Client.WorkspaceOperations.DownloadSourceWithHttpMessagesAsync(String spaceName, String serviceName, String name, Dictionary`2 customHeaders, CancellationToken cancellationToken) in /app/execsvc.client.autogen/WorkspaceOperations.cs:line 161\n   at Microsoft.Azure.DevSpaces.ExecService.Client.WorkspaceOperationsExtensions.DownloadSourceAsync(IWorkspaceOperations operations, String spaceName, String serviceName, String name, CancellationToken cancellationToken) in /app/execsvc.client.autogen/WorkspaceOperationsExtensions.cs:line 49\n   at Microsoft.Azure.DevSpaces.Build.BuildClient.DownloadWorkspaceAsync() in /app/build/BuildClient.cs:line 113","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233029,"Source":"Microsoft.Rest.ClientRuntime","WatsonBuckets":null}, retry.(version=1.0.20190829.2)(clientRequestId=20c87aa0-4fa1-4ab1-be5d-de66978cae31)(correlationRequestId=1bec58f8-bf78-43fa-8c0b-bfe6b5ce3ca2)(ApplicationName=BuildService)(DeviceOperatingSystem=Linux 4.15.0-1052-azure #57-Ubuntu SMP Tue Jul 23 19:07:16 UTC 2019)(Framework=.NET Core 4.6.27817.01)

It would be nice if a error occures in the build container, it bubbles up to the VS gui and cancels the debuging session if possible.

Any idea on how I can get around this problem ?

**Comment by Eneuman** [comment] 2019-09-05 09:25
I think this can be reproduced by doing this:

1) Create a service in VS 2019
2) Select to run it in AKS Dev Space
3) Start debugging so it gets deployed
4) Open AKS Dashboard (AKS Browse)
5) Remove the deployment (but not the service)
6) Deploy again from VS 2019

**Comment by YuzorMa** [comment] 2019-09-05 18:50
Thanks for reporting @Eneuman .  We're investigating the issue and we'll let you know what we find.

**Comment by Eneuman** [comment] 2019-09-05 18:52
Thanks. It's a blocking issue for us atm so please let me know if I can be of any assistans in trouble shooting this.

**Comment by pragyamehta** [comment] 2019-09-05 22:21
Hi Per,

I am not able to reproduce this bug using a simple dotnet web application. Can you confirm if this reproduces for you consistently? Also I am re-iterating the steps you mentioned, just to make sure I understood correctly :
1. Create a dotnet web application in VS 2019
2. Select to run it in AKS Dev Space
3. Start debugging (and optionally stop it)
4. Open AKS dashboard
5. Delete only the deployment
6. Start debugging again from VS 2019.

**Comment by YuzorMa** [comment] 2019-09-13 17:42
This should now be fixed in all regions.

**Closed by YuzorMa** 2019-09-13 17:42 UTC
