### ISSUE TITLE
dev spaces extension breaks Python run cell function

### ISSUE THREAD

**Issue by rustedwizard** [Azure/dev-spaces#356] opened 2020-06-17 03:04 UTC
**Describe the bug**
When Dev Spaces extension installed and enabled, the Run Cell function for python extension stops working.
 
**To Reproduce**
1. In VSCode, install both Azure Dev Spaces and Python extension.
2. Make sure they both are enabled and writing a simple python program like following:
``` python
#%%
greeter = "Hello World"
print(greeter)
```
**Expected behavior**
Click the Run Cell link showed above the code block in VSCode, VSCode should fire up jupyter notebook, and it should output Hello World. 

**Actual behavior**
VSCode failed to launch Jupyter notebook and shows following error message in notification:
>Failed to connect to Jupyter notebook. http://localhost:8888/ TypeError: Only absolute URLs are supported

**Comment by daniv-msft** [comment] 2020-06-18 01:32
Thank you for reporting this, and sorry this came back. This one is actually trickier than the previous one we fixed.
I'm able to reproduce the bug, but I don't know the root cause yet.

This _seems_ to be related to the authentication logic we have in VS Code, but I don't understand how this can conflict with the Python extension yet.
I'll keep investigating this, and I'll update this issue as soon as I have a fix.

**Comment by daniv-msft** [comment] 2020-06-20 01:44
I have a fix for this, but it implied some refactoring on our side. Once we validate that the fix doesn't break anything else, we'll publish a new version of the extension (likely by end of next week).

I'll update this issue once the new version of the extension is published.

**Comment by daniv-msft** [comment] 2020-06-29 18:45
@rustedwizard > I just wanted to keep you updated as we didn't release the new version of the extension last week as I initially thought. We need a bit more time before releasing the new version of the VS Code extension, and we now target to publish it at the beginning of next week.

**Comment by daniv-msft** [comment] 2020-07-08 17:23
Apologies for the back and forth on the release date.
The refactor I made to fix this bug came right at the same time as a bigger change we're working on, and we could hardly release them separately. We plan to have our next release in a couple of weeks, and unfortunately this bug fix won't be released until then.
As usual, I'll update this issue once I have more to share.

**Comment by daniv-msft** [comment] 2020-07-25 01:42
@rustedwizard > We released yesterday the new version of our extension, including the refactoring that was preventing users from running Python cells. I confirm that it now works on my machine.
I'm closing this issue, but please feel free to reopen it if you see any problem.

Thanks again for reporting this bug to us!

**Closed by daniv-msft** 2020-07-25 01:42 UTC
