### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lismarys** [Azure/dev-spaces#82] opened 2019-04-22 14:18 UTC
- Issue Type: `Performance`
- Extension Name: `azds`
- Extension Version: `0.1.120190402`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\TERNURA\azuredevspaces.azds-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by rakeshvanga** [comment] 2019-04-23 18:07
@lismarys Can you also attach your cpu profile?

**Comment by YuzorMa** [comment] 2019-05-28 15:47
@lismarys We have been unable to reproduce this and we cannot investigate it further without the cpu profile from your client when VS Code became unresponsive.  Closing the issue.

**Closed by YuzorMa** 2019-05-28 15:47 UTC
