### ISSUE TITLE
[Dev Space Connect] VS Code error "True"

### ISSUE THREAD

**Issue by Mandur** [Azure/dev-spaces#256] opened 2019-12-17 16:46 UTC
Hello,

We are using Dev Space Connect feature as part of our standard development process, we upgraded recently to the latest version of the CLI and VS code extension. We see sometimes the following error When we try to use the "connect" functions (*Azure Dev Spaces: Redirect an existing service to my local machine*, *Azure Dev Spaces: Redirect an existing/new pod to my local machine*). The VS code extension then fails with the error "true" as shown below.
![image](https://user-images.githubusercontent.com/8555833/71013560-2e0c8100-20f1-11ea-9c85-e10a2337bceb.png). 

I was not able to get any representative logs by using the [recommended troubleshoot mechanism](https://docs.microsoft.com/en-us/azure/dev-spaces/troubleshooting#before-you-begin), but i nevertheless post here below one of the two log file generated by azds (can't upload the other one as it is empty, name was azds-sdk-2019-12-17-16-19-52-25144):

[azds-cli-2019-12-17-16-19-51-25144.txt](https://github.com/Azure/dev-spaces/files/3974317/azds-cli-2019-12-17-16-19-51-25144.txt)

I was unable to get logs from the VS code extension.

We were able to reproduce the issue across development machines from two different companies. It seems the issue arise when we want to use the debugging option from our project folder. It is pretty large and contains some different micro services in the file structure, it also contains some azds.yaml files deeper in the hierarchy. We are currently able to circumvent the issue by creating a new folder, launch vs code from there, and then initiate the debug session remotely. Having the two instance of vs code side by side seems to have exactly same behavior (the one opened from the project doesn't work, the one from the empty folder does).

We are using Azure Dev Spaces CLI 1.0.20191204.4, API v3.2. Azure Dev Spaces extension VS code extension is 2.0.220191204.

Please let me know if I can provide any additional information to help you troubleshoot the issue

Thank you for your Help!

Mikhail

**Comment by daniv-msft** [comment] 2019-12-17 17:14
Hi Mikhail,

Thank you for reporting this issue. This error message is quite unexpected!
Could you please clarify a few things so that I'm sure I get it right?
* You mentioned that you recently upgraded your CLI and VS Code extension. Was the issue also reproducing before you upgrade?
* When the issue reproduces, does it reproduce consistently? Does closing and reopening VS Code help, or do you always have to create the new folder you were mentioning?
* When you see this error message ("true"), is it immediately when you trigger the connect command ("Azure Dev Spaces: Redirect ..."), or after you select your service, your port, etc.?

In parallel, I'm having a look at the code to understand how it could have happened, and how to fix it.
I'll let you know as soon as I have results to share.

Thanks!

**Comment by daniv-msft** [comment] 2019-12-17 18:09
Also, could you please attach the VS Code extension logs?
Here is how to get them:
- Go to `%AppData%\Code\logs\`
- Open the folder with the most recent modified date. Its name should be similar to "20191216T085726".
- Open the folder with a name starting with "exthost" and with the most recent modified date. Warning, the folder with the most recent modified date might not be the one having the highest number (for example, "exthost1" might be more recent than "exthost7").
- Open the "azuredevspaces.azds" folder. This is where you'll find the logs logged by the VS Code extension for the latest session.

**Comment by Mandur** [comment] 2019-12-17 18:20
Hello Daniv,
Thanks for the prompt reply.
No the issues did not occur before, however we used the private preview version before this. azds-0.1.2 installed with the extension file.
The issue stay consistent, restarting VS code or even the computer doesn't seem to fix it (i will try to start from this folder from another computer)
I get the true message imedately after triggering the connect command. I don't get to the options part.

Here is the logs of a session as requested above
[azds-vscode-2019-12-17T16-41-23.594Z.txt](https://github.com/Azure/dev-spaces/files/3974795/azds-vscode-2019-12-17T16-41-23.594Z.txt)

**Comment by daniv-msft** [comment] 2019-12-17 23:05
Thanks for your reply and for sharing the extension logs!
I understand what causes the issue, but I don't unterstand why this doesn't reproduce consistently.

The cause of the failure is that, as part of the connect commands, we execute in the background some kubectl commands. Because the kubectl binary is not embedded with the VS Code extension, we look for it in multiple places where it is usually installed.
This call is done using `fs.exists`, that was recently made asynchronous using `util.promisify` like the rest of our `fs` calls.

This is an error on our side, because `fs.exists` is deprecated and doesn't work the same way as newer `fs` methods.
When we check for the existence of the kubectl file, `fs.exists` calls its callback with a boolean as first argument whereas `util.promisify` expects an error as first argument, thus resulting in an exception thrown as "true". This explains the message you see.

What is tricky though is that if the argument is `false` (`kubectl` binary not found), then because the implementation of `util.promisify` doesn't check explicitly for `null`/`undefined`, this `false` value is not considered as an error and the function returns successfully with value `undefined`.
Then, our code interprets this `undefined` as `false`, which actually corresponds to the expected result given that we didn't find the `kubectl` binary... This behavior might explain why this issue doesn't reproduce all the time: as long as we can't find the `kubectl` binary, the issue won't show and we'll default to the `kubectl` binary declared in the PATH.

This is definitely a bug on our side, and we're working on a fix.

However, what I don't understand is why this sometimes work. I would expect this to throw every time we find the `kubectl` binary, so almost in every case. I also don't understand why creating a new folder would help with this issue.

* Do you have the Azure Dev Spaces CLI installed on the machine where you reproduce this issue (you can try to run `azds --version` in a command prompt)?
* Are the other users of connect commands in your company having the Azure Dev Spaces CLI installed?
* Do you use Windows or MacOS on the machine where you reproduce this issue? This bug shouldn't reproduce on Linux.
* I'm wondering if this could be due to the Node.js version used by VS Code. Could you please open VS Code, open `Help > About` and attach a capture of the menu showing the versions installed locally?

Thanks!

**Comment by Mandur** [comment] 2019-12-18 07:03
This is indeed an interesting issue. I tried again the morning, and could reproduce the issue exactly as described above.
As requested:

Here is the result of azds --version. If i remember correctly I updated it in the last days
Azure Dev Spaces CLI
1.0.20191204.4
API v3.2

I use Windows, I Can ask a colleague on MacOS to reproduce. I will reboot and check on Linux and report back here.

Here is the visual studio code version report:
Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

In addition here is the kubectl version, I see i am not on latest, could that be an issue?
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"2640ac46d96791a135961425127d9c2f7e184924", GitTreeState:"clean", BuildDate:"2019-11-14T04:58:54Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Mandur** [comment] 2019-12-18 08:07
I tried on Linux and the problem did not occur as you expected.

Here is the report of my colleague were we could reproduce the error (note that we are bound to two different AKS clusters)
```
    $ azds --version
Azure Dev Spaces CLI
1.0.20191212.6
API v3.2
 
Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
 
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:14:29Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"} 
```

**Comment by Mandur** [comment] 2019-12-18 09:30
Hello, 

We did some more testing, on OS X we were able to start the commands form the folder without issues. 
Additionally, we tried on another colleague and we were able to successfully launch the command (Windows 10)

**Comment by daniv-msft** [comment] 2019-12-18 20:05
Thank you for testing all these!
I believe this issue is independent from the actual kubectl binary installed, as this bug happens in our code before we even run kubectl commands.
Also, at this point the kubeconfig shouldn't be used yet, so I expect the issue isn't due to this environment variable being set.

My initial expectation was that there would be discrepancies between the Node.js versions used in your team, and that some of them would include a fix to make `util.promisify` work with `fs.exists`.
As this is not the case according to the data you shared, it means that something else creates this discrepancy.

In order to get more data, I would like to test a custom version of the VS Code extension including the fix mentioned above as well as more logs.
If that's OK for you, I'll contact you in private to share the updated package.

Thanks again for all your help so far!

**Comment by Mandur** [comment] 2019-12-18 20:24
Sure with pleasure!

**Comment by Mandur** [comment] 2019-12-19 07:42
I can confirm the proposed solution fixed the error on both the install we saw it. Thank you very much for fixing

**Comment by daniv-msft** [comment] 2019-12-19 16:33
That's great, thank you Mikhail!
I'll close this issue once the fix is released publicly, at the beginning of January.

Thanks again for reporting this issue and helping us investigate it!

**Comment by daniv-msft** [comment] 2020-01-18 01:31
The new version of the VS Code extension including this fix was released today!
I'm closing this issue, but please let us know if you run into any other problem.

**Closed by daniv-msft** 2020-01-18 01:31 UTC
